apiVersion: v1
kind: ConfigMap
metadata:
  name: agency-base-config
  namespace: staging
data:
  APP_NAME: Agency base service
  APP_HOME: 127.0.0.1
  PORT: "8080"
  DB_CLIENT: postgres
  DB_HOST: postgres-emple
  DB_PORT: "5432"
  REDIS_HOST: redis-emple
  REDIS_PORT: "6379"
  DB_DATABASE: insurance_agency_base_mgt
 
 

---
apiVersion: v1
kind: Secret
metadata:
  name: agency-base-secret
  namespace: staging
type: Opaque
data:
  PLACEHOLDER: OUo3Wkh2Y2h1MWh

