apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deploy.yaml
- service.yaml
- configmap.yml

images:
  - name: REGISTRY/PROJECT_ID/IMAGE
    newName: emplestagingrepo.azurecr.io/ca/agency-base-service