apiVersion: v1
kind: Service
metadata:
  name:  emple-agency-base-service
  namespace: staging
spec:
  ports:
  - name: http
    port: 80             
    protocol: TCP            
    targetPort: 8080     
  selector:                  
    app:  emple-agency-base-service
  type: ClusterIP             

