---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agency-base-config
  namespace: dev
data:
  APP_NAME: Agency base service
  APP_HOME: 127.0.0.1
  PORT: "8080"
  DB_CLIENT: postgres
  DB_HOST: 101.10.10.30
  DB_PORT: "5432"
  REDIS_HOST: redis-service.dev.svc.cluster.local
  REDIS_PORT: "6379"
  DB_DATABASE: insurance_agency_base_mgt
  REDIS_USERNAME: default
  API_GATEWAY_URL: "https://emple-general-apigateway-service-dev.incanalis.com/v1"
  API_GATEWAY_SECRET_KEY: "0ffeaec3-f53a-4563-a7d8-0d1d4d206c23"
  FINANCE_SERVICE_URL: "https://emple-shared-payments-service-dev.incanalis.com/v1/payments"
  JWT_SECRET: "Canalis"
  SESSION: "3600"
  SESSION_SECRET: "Canalis"
  MAIL_HOST: "gmail"
  MAIL_SERVICE: "gmail"
  MAIL_PORT: "465"
  MAIL_USERNAME: "add_your_value"
  MAIL_PASSWORD: "add_your_passsword"
  FROM_EMAIL: "Emple"
  FROM_NAME: "Emple"
  QUEUE_ATTEMPTS: "3"
  QUEUE_DELAY: "5000"
  OBS_ACCESS_KEY_ID: "IF4HI2F7PS9JP9G4NHDY"
  OBS_SECRET_ACCESS_KEY: "plm4vJOdT15EssRSKWQJa90ztwIhk54a6DpvzQjX"
  OBS_SERVER_URL: "obs.ap-southeast-1.myhuaweicloud.com"
  OBS_BUCKET_NAME: "agency-documents"
  MAX_CONCURRENT_UPLOADS: "5"
  REFRESH_TOKEN_SESSION: "360000000"
 
 
apiVersion: v1
kind: Secret
metadata:
  name: agency-base-secret
  namespace: dev
type: Opaque
data:
  # REDIS_PASSWORD: cjFHTmhsbmR5VE5UMU41bA==
  # REDIS_USERNAME: Y2FuYWxpcy1yZWRpcy1kZXY=
  DB_PASSWORD: OUo3Wkh2Y2h1MWhzS3JsOA==
  DB_USERNAME: Y2FuYWxpc3VzZXI=

