export enum DB_TABLES {
  MODULES = "modules",
  AUDIT_TRAILS = "audit_trails",
  USERS = "users",
  WALLETS = "wallets",
  IDVERIFICATION = "id_verifications",
  OTP = "otps",
  ACTIVITYLOG = "activity_logs",
  PERMISSIONS = "permissions",
	ROLES = "roles",
	ROLE_PERMISSIONS = "role_permissions",
	POLICIES = "policies",
	NOTIFICATIONS = "notifications",
	TRANSACTIONS = "transactions",
	ACTION_REASONS = "action_reasons",
	POLICY_BENEFICIARY = "policy_beneficiaries",
}
