export const policyValidationRules = {
  supervisorId: "required|string",
  customerId: "required|string",
  productId: "required|string|min:5|max:50",
  customerType: "required|string",
  businessType: "required|string|min:3|max:50",
  startDate: "required|date",
  endDate: "required|date",
  // agentId: "required|string",
  brokerId: "string",
  relationshipManagerId: "string",
  sbu: "string|min:3|max:50",
  sbuId: "required|string",
  branch: "string|min:3|max:50",
  source: "required|string|min:3|max:50",
  sumInsured: "required|integer",
  premium: "required|integer|min:0",
  ourSharePercentage: "required|integer|min:0|max:100",
  classOfBusinessId: "required|string",
  currency: "required|string",
  // cbaStatus: "required|string",
  savingsGoal: "string|min:3|max:100",
  // paymentFrequency: "required|string|in:Monthly,Quarterly,Annually",
  // annualRiskCover: "required|integer",
  // annualRiskPremuim: "integer|min:0",
};
